import { Product } from "./types/Product";

export const sampleProducts:Product[] = [
 {
 name: 'nike Slim shirt',
 slug: 'nike-slim-shirt',
 category: 'Shirts',
 image: '../images/p1.jpg',
 price: 120,
 countInStock: 10,
 brand: 'Nike',
 rating: 4.5,
 numReviews: 10,
 description: 'high quality shirt',
},
{
 name: 'Adidas Fit shirt',
 slug: 'adidas-fit-shirt',
 category: 'Shirts',
 image: '../images/p2.jpg',
 price: 100,
 countInStock: 20,
 brand: 'Adidas',
 rating: 4,
 numReviews: 10,
 description: 'high quality shirt',
},
{
    name: 'Lacoste Free pants',
    slug: 'lacoste-free-pants',
    category: 'Pants',
    image: '../images/p3.jpg',
    price: 220,
    countInStock: 0,
    brand: 'lacoste',
    rating: 4.8,
    numReviews: 17,
    description: 'high quality shirt',
   },
   {
    name: 'Nike Slim pants ',
    slug: 'nike-slim-pants',
    category: 'Pants',
    image: '../images/p4.jpg',
    price: 78,
    countInStock: 10,
    brand: 'Nike',
    rating: 4,
    numReviews: 10,
    description: 'high quality shirt',
   },
]